import Nav from "@/components/nav";
import { Playfair_Display, Montserrat } from "next/font/google";
import HeroUIWrapper from "../wrappers/herouiwrapper";
import "./globals.css";



const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const montSerrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${montSerrat.variable} antialiased`}
      >

        <HeroUIWrapper>
          <Nav></Nav>
          <main>
            {children}
          </main>
        </HeroUIWrapper>
      </body>
    </html>
  );
}
